### ISSUE TITLE
QT5 support

### ISSUE THREAD

**Issue by GreenSokrates** [coin3d/quarter#43]
Is there no Qt5 support? Or is the README just outdated?

**Comment by VolkerEnderlein** [comment]
The README is not up to date. Have a look at the GUI toolkit section at [Build with CMake](https://github.com/coin3d/coin/wiki/BuildWithCMake#gui-toolkit-soqt-sowin-soxt-quarter-build-configuration-using-cmake) how to build quarter with CMake. If there are undocumented switches you might also try calling `cmake -L .` in the build directory to get a full list of all options.

**Comment by GreenSokrates** [comment]
Thank you very much! Works like a charm
