### ISSUE TITLE
Qt version check

### ISSUE THREAD

**Issue by limingyin18** [coin3d/quarter#58]
QOpenGLWidget introduce since Qt 5.4.

https://github.com/coin3d/quarter/blob/6297049ae09920e945d8c63671e1d907ecfa8ebb/include/Quarter/QuarterWidget.h#L42-L47

**Comment by VolkerEnderlein** [comment]
Thanks for your comment. This should read the other way round. QGLWidget has been removed since Qt6 and therefore cannot be used anymore. As QGLWidget provided some additional features that have not been added to QOpenGLWidget we wanted to stick as long as possible to the QGLWidget.

**Comment by limingyin18** [comment]
Thanks for reply. Get the point.
