### ISSUE TITLE
QuarterWidgetPlugin crash Qt Designer with Segmentation fault when build with Qt6

### ISSUE THREAD

**Issue by podsvirov** [coin3d/quarter#61]
I detect this for [Quarter](https://packages.msys2.org/base/mingw-w64-quarter) plugin when [updating](https://github.com/msys2/MINGW-packages/pull/19940) package and trying switch to `Qt6` from `Qt5` on `Windows`.
Currently we still use [Qt5](https://github.com/msys2/MINGW-packages/compare/38275028daec10bc0b431947331865a24255146d..bad77ba80a8dd76850287999a6a28f7d5219a15d).

**Comment by VolkerEnderlein** [comment]
Thanks for the report, I'll have a look into it.

**Comment by podsvirov** [comment]
Currently we only build 64-bit packages with gcc and clang compilers. And just for note: designer.exe (Qt5), but designer-qt6.exe (Qt6).

**Comment by VolkerEnderlein** [comment]
Just released version v1.2.1 that fixes the issue. Thanks for your ongoing contribution to Coin development. It is highly appreciated.

**Comment by podsvirov** [comment]
Thanks for quick fix! Newlest [package](https://github.com/msys2/MINGW-packages/pull/19952) in the repo. Binary packages pending.
